iabbrev wemail jj.asghar@peopleadmin.com
iabbrev hemail jjasghar@gmail.com

" common misspelled words
iabbrev teh the
iabbrev accross across

set laststatus=2
set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

" fix copying in with the stupid indendets
set autoindent

set hidden " to move hidden buffers easyly

" spelling
" toggle spellchecking on and off with `,s`
let mapleader = ","
nmap <silent> <leader>s :set spell!<CR>
" set region for dict
set spelllang=en_us
set spell

set autochdir " so i don't have to keep traversing directories

" stolen from SneakyPhil
cmap w!! % ! sudo tee 2> /dev/null %

" stolen from vimgolf.com
set nocompatible        " use vim defaults
set scrolloff=3         " keep 3 lines when scrolling
set ai                  " set auto-indenting on for programming
set number

set showcmd             " display incomplete commands
set nobackup            " do not keep a backup file
set ruler               " show the current row and column

set hlsearch            " highlight searches
set incsearch           " do incremental searching
set showmatch           " jump to matches when entering regexp
set ignorecase          " ignore case when searching
set smartcase           " no ignorecase if Uppercase char present

set visualbell t_vb=    " turn off error beep/flash
set novisualbell        " turn off visual bell

set backspace=indent,eol,start  " make that backspace key work the way it should

syntax on               " turn syntax highlighting on by default
filetype on             " detect type of file
filetype indent on      " load indent file for specific file type

highlight NonText    ctermfg=Red

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" from helo
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows



"set nostartofline

"let os = substitute(system('uname'), '\n', '', '')

"if has('gui_running')
 " generic GUI settings go here

"if os == 'Darwin' || os == 'Mac'
 " MacVim-specific settings go here

"elseif os == 'Linux'        
 " GVim-specific settings go here

"endif

"else      
 " generic CLI Vim settings go here

"if os == 'Darwin' || os == 'Mac'        
 " Mac OS X-specific CLI Vim settings go here

"elseif os == 'Linux'
 " Linux-specific CLI Vim settings go here

"endif

"endif

